### ISSUE TITLE
Peer review and branching model

### ISSUE THREAD

**Issue by AdeebNqo** [Redgram/redgram-for-reddit#1]
Hello,

I have a few suggestions.
### Branching model

The status on the `README` file currently () says:

> Implementing the image manager that will be responsible for viewing the possible image types and sizes 

There is currently no code in the master branch. I would to suggest the adoption of a branching model. Specifically,
I suggest the one described [int this article](http://nvie.com/posts/a-successful-git-branching-model/)
## Peer review

Can we also use a peer review system. I suggest [gerrit](http://gerrithub.io/) since it allows github sign in.
## UI

I do not understand what is going on with the Wireframes on the `README`. Can we please re-do them, and aim use
[material design](http://www.google.com/design/spec/material-design/introduction.html)

**Comment by mhdatie** [comment]
They all seem good. I am willing to push the code but since you suggested the branching model, I will have to look at it or find another alternative. As for Gerrit, it's a great tool for pull requests, I will make sure this project adopts it.

The UI part in the README was an initial one and is just used for quick presentation, it has changed and there will be up to 6 different types of items (each with their own layout) when we list the data. Everything will be Material.

Please be aware that this will be a boilerplate for a single endpoint only and will be using up-to-date libraries and good documentation for anyone willing to adopt its structure or help simplify it.

I am willing to use the name `Redgram for Reddit` for my official app in the future.

**Comment by mhdatie** [comment]
@AdeebNqo added the source code

**Comment by AdeebNqo** [comment]
I saw that, thanks. I am going to go over it when I get the chance. Please just create a `dev` branch so that we will work on it until we release something.

**Comment by mhdatie** [comment]
created.
