### ISSUE TITLE
Account Manager

### ISSUE THREAD

**Issue by ScottCooper92** [Redgram/redgram-for-reddit#5]
I'm going to advocate that you remove functionality from presenters related to a user performing an action on something. Things like voting, reporting, saving etc will crop up quite often which means code is likely to be duplicated across presenters.

It would probably make sense to inject an AccountManager into each presenter that takes care of these kind of things. It can have a method for each action that can be performed and take the id of the Thing to perform it on and provide callbacks to let the Presenter know whether or not the action succeeded.

**Comment by mhdatie** [comment]
Thanks for the suggestion. I agree, since I will have to do those operations in comments eventually. Why did you think of AccountManager? 

Currently any action I perform uses the currently logged in user. I'm using realm to hold the session information which can only be one entry. There is no support for multiple users yet and I want to handle that with Realm in the future. 

I'm not sure whether it's a wise decision excluding AccountManager in the first place but the only advantage I see in it is if the user wanted to manage their accounts from the device settings. 

Otherwise, we can just have a class like you suggested that deals with common ops. What do you think?

**Comment by ScottCooper92** [comment]
By AccountManager I didn't mean the Android framework, I meant creating a custom class that takes care of all user related functionality. I've attempted to use AccountManager in the past but it's too limited in terms of what you can store against the user (no subreddits for example).

The custom AccountManager will obviously manage state and might make it easer to allow users to user the app without logging in, attempting to upvote would result in the Manager giving back an error message which can be displayed to the user.

I'm in the process of creating my own reddit app so I'm planning on doing something similar but until I've actually completed it I can't tell you how well it works.

**Comment by mhdatie** [comment]
I remember seeing a comment on /r/redditdev that they will require users to use OAuth in the future (no public api), and that's why I only focused on the user being logged in always. I don't intend to use the public API anymore. 

Look at my RedditService: https://github.com/Redgram/redgram-for-reddit/blob/master/Redgram/app/src/main/java/com/matie/redgram/data/network/api/reddit/base/RedditService.java

It handles `401` errors and re authenticates the user as required.

**Comment by ScottCooper92** [comment]
I think what they meant is that all third parties will be required to authenticate regardless of whether the user is logged in or not, see here for more information https://github.com/reddit/reddit/wiki/OAuth2#application-only-oauth

**Comment by mhdatie** [comment]
Yes, I just saw it https://www.reddit.com/r/redditdev/comments/4duy13/are_there_any_api_restrictions_if_not_using_oauth/

**Comment by ScottCooper92** [comment]
I'm going to take a look at this on a small project myself and let you know how it goes, if it works I'll do a PR

**Comment by mhdatie** [comment]
Thank you, I think as long as handling the authentication grant type and status is in the service, application oauth can easily be implemented
